import { useState } from "react";
import { ArrowRight, Clock3, MessageCircle, Search, Users } from "lucide-react";
import Footer from "../components/common/Footer";

const categories = [
    { name: "General STEM", count: "248 conversations", icon: "✦", color: "text-red-500 bg-red-50" },
    { name: "Robotics & Electronics", count: "186 conversations", icon: "⚙", color: "text-cyan-600 bg-cyan-50" },
    { name: "Coding Corner", count: "142 conversations", icon: "</>", color: "text-blue-600 bg-blue-50" },
    { name: "Projects & Showcases", count: "96 conversations", icon: "↗", color: "text-green-600 bg-green-50" },
];

const discussions = [
    { title: "What are you building this month?", category: "Projects & Showcases", author: "Aarav Mehta", replies: 18, time: "12 min ago", initials: "AM" },
    { title: "Help me choose a motor driver for my bot", category: "Robotics & Electronics", author: "Riya Shah", replies: 12, time: "1 hour ago", initials: "RS" },
    { title: "Best resources to start with Python?", category: "Coding Corner", author: "Kabir Joshi", replies: 27, time: "3 hours ago", initials: "KJ" },
    { title: "Share your science fair wins and lessons", category: "General STEM", author: "Anaya Rao", replies: 9, time: "Yesterday", initials: "AR" },
];

function Forum() {
    const [query, setQuery] = useState("");
    const filtered = discussions.filter((discussion) => discussion.title.toLowerCase().includes(query.toLowerCase()));

    return <main className="w-full overflow-hidden bg-white text-slate-950"><section className="relative overflow-hidden bg-[#0f172a] px-6 py-20 text-white sm:px-8 lg:px-10 lg:py-24"><div className="pointer-events-none absolute inset-0 opacity-[0.09]" style={{ backgroundImage: "linear-gradient(rgba(255,255,255,.6) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.6) 1px, transparent 1px)", backgroundSize: "40px 40px" }} /><div className="pointer-events-none absolute -bottom-36 -right-20 h-80 w-80 rounded-full border-[20px] border-red-500/10" /><div className="relative z-10 mx-auto max-w-6xl"><div className="flex items-center gap-4"><span className="h-px w-12 bg-red-500" /><span className="text-xs font-bold uppercase tracking-[0.3em] text-red-400">The STEMSAGE community</span></div><div className="mt-7 grid gap-10 lg:grid-cols-[1fr_0.8fr] lg:items-end"><div><h1 className="max-w-3xl text-5xl font-black leading-[1.02] tracking-[-0.05em] sm:text-6xl lg:text-[72px]">Ask. Share. <span className="text-red-500">Build.</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-slate-400 sm:text-lg">Our forum is a friendly space for learners, mentors, makers, and educators to learn in public and help each other move forward.</p></div><div className="flex gap-8 border-l border-white/10 pl-7"><div><div className="text-3xl font-black">1.2k<span className="text-red-500">+</span></div><div className="mt-1 text-xs font-bold uppercase tracking-widest text-slate-500">Members</div></div><div><div className="text-3xl font-black">640<span className="text-red-500">+</span></div><div className="mt-1 text-xs font-bold uppercase tracking-widest text-slate-500">Topics</div></div></div></div></div></section>

        <section className="mx-auto max-w-6xl px-6 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mb-10 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.28em] text-slate-400">Find your people</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Explore discussions</h2></div><button type="button" className="inline-flex w-fit items-center gap-2 rounded-full bg-red-600 px-5 py-3 text-sm font-bold text-white transition hover:bg-red-700">Start a discussion <ArrowRight size={16} /></button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map((category) => <button type="button" key={category.name} className="group rounded-2xl border border-slate-200 p-5 text-left transition hover:-translate-y-1 hover:border-red-200 hover:shadow-lg"><div className={`flex h-11 w-11 items-center justify-center rounded-xl text-lg font-black ${category.color}`}>{category.icon}</div><h3 className="mt-5 font-black">{category.name}</h3><p className="mt-1 text-xs font-medium text-slate-400">{category.count}</p><ArrowRight size={16} className="mt-5 text-slate-300 transition group-hover:translate-x-1 group-hover:text-red-500" /></button>)}</div>

            <div className="mt-20 grid gap-10 lg:grid-cols-[1fr_280px]"><div><div className="mb-5 flex flex-col justify-between gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-center"><h2 className="text-2xl font-black">Latest conversations</h2><label className="flex items-center gap-2 rounded-full border border-slate-200 px-4 py-2 text-sm text-slate-400"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search topics" className="w-32 bg-transparent outline-none placeholder:text-slate-400" /></label></div><div className="divide-y divide-slate-100">{filtered.map((discussion) => <article key={discussion.title} className="group flex gap-4 py-5"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-slate-100 text-xs font-black text-slate-600">{discussion.initials}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold transition group-hover:text-red-600">{discussion.title}</h3><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-slate-500">{discussion.category}</span></div><p className="mt-2 text-xs text-slate-400">Started by <span className="font-semibold text-slate-600">{discussion.author}</span></p></div><div className="hidden shrink-0 items-center gap-4 text-xs font-semibold text-slate-400 sm:flex"><span className="flex items-center gap-1"><MessageCircle size={14} />{discussion.replies}</span><span className="flex items-center gap-1"><Clock3 size={14} />{discussion.time}</span></div></article>)}{filtered.length === 0 && <p className="py-8 text-sm text-slate-500">No discussions match your search.</p>}</div></div><aside className="h-fit rounded-2xl bg-slate-50 p-7"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white text-red-500 shadow-sm"><Users size={21} /></div><h3 className="mt-5 text-xl font-black">New here?</h3><p className="mt-3 text-sm leading-7 text-slate-500">Introduce yourself, ask your first question, or share what you’re learning.</p><button type="button" className="mt-6 text-sm font-bold text-red-600 transition hover:text-red-700">Join the conversation <span className="ml-1">→</span></button></aside></div></section></main>;
}

export default Forum;
